### ISSUE TITLE
Bot Isn't Starting Up

### ISSUE THREAD

**Issue by RomanGoddess** [SpEcHiDe/FilesBot#1]
I get no error on heroku logs but the bot doesn't respond to start command.

**Comment by SpEcHiDe** [comment]
you need to goto this URL: https://api.telegram.org/botTOKEN/setWebhook?url=https://yourherokuappname.herokuapp.com/ . the trailing "/" is important.

**Comment by Mrvishal2k2** [comment]
But why this error when i access that site 😒
{"ok":false,"error_code":404,"description":"Not Found"}

I accessed https://api.telegram.org/mybotTOKEN/setWebhook?url=https://myherokuappname.herokuapp.com/
