### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RomanGoddess** [SpEcHiDe/FilesBot#13]
Error: Class "Telegram\MessageId" not found in /app/vendor/skrtdev/novagram/src/Telegram/Types/MessageId.php:11
Stack trace:
#0 /app/vendor/composer/ClassLoader.php(444): include()
#1 /app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 /app/vendor/skrtdev/novagram/src/NovaGram/Bot.php(448): Composer\Autoload\ClassLoader->loadClass()
#3 /app/vendor/skrtdev/novagram/src/NovaGram/Bot.php(413): skrtdev\NovaGram\Bot->createObject()
#4 /app/vendor/skrtdev/novagram/src/NovaGram/Bot.php(387): skrtdev\NovaGram\Bot->JSONToTelegramObject()
#5 /app/vendor/skrtdev/novagram/src/Telegram/Type.php(76): skrtdev\NovaGram\Bot->APICall()
#6 /app/web/index.php(29): skrtdev\Telegram\Type->__call()
#7 /app/vendor/skrtdev/novagram/src/NovaGram/HandlersTrait.php(101): {closure}()
#8 /app/vendor/skrtdev/novagram/src/NovaGram/HandlersTrait.php(91): skrtdev\NovaGram\Bot->skrtdev\NovaGram\{closure}()
#9 /app/vendor/skrtdev/novagram/src/NovaGram/HandlersTrait.php(76): skrtdev\NovaGram\Bot->skrtdev\NovaGram\{closure}()
#10 /app/vendor/skrtdev/novagram/src/NovaGram/Dispatcher.php(57): skrtdev\NovaGram\Bot->skrtdev\NovaGram\{closure}()
#11 /app/vendor/skrtdev/novagram/src/NovaGram/Dispatcher.php(72): skrtdev\NovaGram\Dispatcher->skrtdev\NovaGram\{closure}()
#12 /app/vendor/skrtdev/novagram/src/NovaGram/Bot.php(295): skrtdev\NovaGram\Dispatcher->handleUpdate()
#13 /app/vendor/skrtdev/novagram/src/NovaGram/Bot.php(313): skrtdev\NovaGram\Bot->idle()
#14 [internal function]: skrtdev\NovaGram\Bot->__destruct()
#15 {main}

**Comment by aryan5610** [comment]
Same error but bot working fine
