### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by Brooklyn888** [SpEcHiDe/FilesBot#23]
Please Add Mongo DB Support to the Repository.Please 😔😔😔😔🙏🙏🙏🙏.Please.

**Comment by SpEcHiDe** [comment]
https://te.legra.ph/file/bb2449c5d737bc9d4a137.jpg

**Comment by Brooklyn888** [comment]
Please Sir Add Mongo DB Support to files Bot Repo . Please..
