### ISSUE TITLE
Bot Isn't Hiding Sender/Forwarder Profile/Channel

### ISSUE THREAD

**Issue by RomanGoddess** [SpEcHiDe/FilesBot#3]
Identity Of The Sender Is Written & Can Be Clickable By Anyone Else Who Starts The Bot With The Given Link.. 

Below Is A Screenshot For Better Understanding. Please Fix It So Nobody Click & View Sender's Profile.. Also If It's Forwarded From A Channel To The Bot, The Channel Forwarded From Will Appear There If Anyone Starts The Link

![Screenshot_20201110_200000](https://user-images.githubusercontent.com/53878781/98718928-5a775e80-238f-11eb-95c0-4f6ce626d88a.jpg)

**Comment by AhyaH-YHWH** [comment]
Yes, Since Bot API 5, has Copy Message, it would be Nice, to have Forward as Copy, for All messages, and Hide sender
